source("https://rubygems.org")

gem("pg")
gem("pry")
gem("rspec")
gem("capybara")
gem("sinatra")
gem("sinatra-contrib", :require => "sinatra/reloader")
gem("sinatra-activerecord")
gem("rake")
gem("launchy")
